#!/usr/bin/env python3
import sys, os, getpass, crypt


username = sys.argv[1]
passwdline = "{}:x:1000:1000::/home/{}:/bin/bash\n".format(username, username)

password = getpass.getpass('Password: ')
passwordhash = crypt.crypt(password)
shadowline = "{}:{}:::::::\n".format(username, passwordhash)

# write files
if !os.path.isdir('users'): os.mkdir('users')

listfile = open('users/list', 'a')
listfile.write("{}\n".format(username))
listfile.close()

shadowfile = open('users/shadow', 'a')
shadowfile.write(shadowline)
shadowfile.close()
