#!/usr/bin/env python3
import sys, os, getpass, crypt


username = sys.argv[1]

password = getpass.getpass('Password: ')
passwordhash = crypt.crypt(password)
shadow = "{}:{}:::::::\n".format(username, passwordhash)

file = open('users', 'a')
file.write(shadow)
file.close()
